repos:
-   repo: local
    hooks:
    - id: system
      name: black
      entry: python -m black
      language: system
      args: ['--safe']
      files: \.py$
-   repo: local
    hooks:
    - id: system
      name: flake8
      entry: python -m flake8
      language: system
      args: [
        '--ignore=E203,E266,E501,W503,F403,F401'
      ]
      files: \.py$
      # E203 "whitespace before ':'"
      # E266 "Too many leading '#' for block comment"
      # E501 "Line too long (82 > 79 characters)"
      # W503 "line break before operator"
      # F403 "'from module import *' used"
      # F401 "Module imported but unused"cls
-   repo: local
    hooks:
    - id: system
      name: pydocstyle
      entry: python -m pydocstyle
      language: system
      args: [
              '--select=D1',
              '--match=(?!tests).*\.py,pyqtt_application*'
        ]
      files: \.py$
      # Check for docstring presence only.
      # Don't require docstrings for tests.
      # Execute only at module level.
